name: deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: install
        run: |
          npm install
          cd 3.5_character_card_generator
          pwd
          npm install
          cd ../
      - name: build
        run: |
          npm run docs:build
          cd 3.5_character_card_generator
          pwd
          npx vite build --base="./"
          cd ../
          pwd
      - name: copy
        run: |
          mkdir docs/.vuepress/dist/cg
          mv 3.5_character_card_generator/dist/* docs/.vuepress/dist/cg/
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/.vuepress/dist # The folder the action should deploy.
